### ISSUE TITLE
Segmentation fault when compiling this OpenCL kernel

### ISSUE THREAD

**Issue by owuntu** [HSAFoundation/CLOC#10]
I am encountering a segmentation fault when compiling this OpenCL kernel to Brig or Hsail text:
__kernel void test_kernel(__global int* pVal) {
    pVal[1] = 123;
    if (pVal[2] == 0) {
      while (pVal[0] == 0) {
        pVal[1] = 123;
      }
    }
    pVal[1] = 321;
}

Here is the cloc.sh compilation console output:
0  llc             0x0000000000b1a3af
1  llc             0x0000000000b1a724
2  libpthread.so.0 0x00007f8b73258340
3  llc             0x0000000000483c70
4  llc             0x0000000000ac2e4f
5  llc             0x0000000000ac3243
6  llc             0x0000000000ac34ff
7  llc             0x0000000000ac363c
8  llc             0x000000000042bf76
9  libc.so.6       0x00007f8b72ea1ec5 __libc_start_main + 245
10 llc             0x0000000000438861
Stack dump:
0.	Program arguments: /opt/amd/cloc/bin/llc -O2 -march=hsail-64 -filetype=asm -o /tmp/cloc4242/trap.hsail /tmp/cloc4242/trap.opt.bc 
1.	Running pass 'Function Pass Manager' on module '/tmp/cloc4242/trap.opt.bc'.
2.	Running pass 'HSAIL control dependency analysis' on function '@__OpenCL_test_kernel_kernel'
/opt/amd/cloc/bin/cloc.sh: line 333:  4262 Segmentation fault      (core dumped) $HSA_LLVM_PATH/$CMD_LLC -o $TMPDIR/$FNAME.hsail $TMPDIR/$FNAME.opt.bc
ERROR:  The following command failed with return code 139. 
/opt/amd/cloc/bin/llc -O2 -march=hsail-64 -filetype=asm -o /tmp/cloc4242/trap.hsail /tmp/cloc4242/trap.opt.bc

Notice, if the while loop is empty, or without the if condition, cloc.sh compilation runs fine.

**Comment by gregrodgers** [comment]
Definitely a bug in opt in llvm 3.2.  I expect a move to llvm 3.X before fixing this.   But your code has a serious case of false sharing.   With no other knowledge, an optimizing compiler would sense infinite loop.    Change "while ..." to 

while (atomic_load((global atomic_int *)&pVal[0]) == 0 ) { 

and it will compile.   But other memory synchronization may be needed to coordinate your intentions with the host or other kernels.  If you really want to live dangerously, turn down optimization and it will also compile. 

cloc.sh -opt 1 test_kernel.cl

Greg

**Comment by alex-t** [comment]
This is already fixed. Should work with the latest compiler builds.

**Comment by gregrodgers** [comment]
Works with HSA code object.   The hsail path with HLC3.2 requires -opt 1 for this to work.  Closing .
