### ISSUE TITLE
add Ubuntu 16.04 install instructions

### ISSUE THREAD

**Issue by nerdralph** [HSAFoundation/CLOC#22]
Same as Ubuntu 14.04, except:
'echo deb [arch=amd64] http://packages.amd.com/rocm/apt/debian/ xenial main > /etc/apt/sources.list.d/rocm.list'

**Comment by johndeppe** [comment]
This issue is further aggravated by the amdcloc package no longer existing on the ROCM apt server. May we please have updated install instructions, or a new package?

**Comment by jedwards-AMD** [comment]
The CLOC packaging is no longer supported. Please use hcc for OpenCL code compilation.
