### ISSUE TITLE
How can I compile a sample in AMD APP SDK using CLOC?

### ISSUE THREAD

**Issue by LiXiuhong** [HSAFoundation/CLOC#3]
I have installed AMD-hsa-driver, hsa-runtime and CLOC. Now I can compile and run the samples in examples of CLOC correctly. I have some benchmarks from AMD APP SDK3.0, can I compile them using CLOC?

**Comment by srp1970** [comment]
No, the CLOC currently supports 1.2 OpenCL features only. You have to wait
for upgradation of this compiler to OpenCL 2.0 features.

Prakash

On Mon, Jan 26, 2015 at 11:15 AM, LiXiuhong <notifications@github.com>
wrote:

> I have installed AMD-hsa-driver, hsa-runtime and CLOC. Now I can compile
> and run the samples in examples of CLOC correctly. I have some benchmarks
> from AMD APP SDK3.0, can I compile them using CLOC?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HSAFoundation/CLOC/issues/3>.
>



-- 
With Best Regards
Prakash Raghavendra

**Comment by LiXiuhong** [comment]
I think what you mean is that when we disscus whether CLOC support OpenCL, we mean the kernel parts not host code. That is CLOC currently supports the kernel part of OpenCL 1.2. Is that correct?

Because when I compile a OpenCL benchmark, I need to link OpenCL.so to it. In this way I can succeed in compiling, but when I run the binary, it exists the following errors: Error: clGetPlatformIDs failed. Error code : CL_PLATFORM_NOT_FOUND_KHR

So I think if there is any one OpenCL runtime API existing in my program (host code), it cannot run correctly in the HSA enabled system. I think the reason is that I haven't installed the related GPU runtime environment, but HSA-AMD-driver instead. Is that correct?

Thank you! 

--
Best Regards,
Xiuhong

**Comment by srp1970** [comment]
Yes, CLOC supports kernel source for 1.2. HSAIL RT does not yet support
OpenCL. You have to run OpenCL apps on Catalyst driver, which is installed
when you install Catalyst driver (on both Windows and Linux).

Prakash

On Mon, Jan 26, 2015 at 4:34 PM, LiXiuhong <notifications@github.com> wrote:

> I think what you mean is that when we disscus whether CLOC support OpenCL,
> we mean the kernel parts not host code. That is CLOC currently supports the
> kernel part of OpenCL 1.2. Is that correct?
>
> Because when I compile a OpenCL benchmark, I need to link OpenCL.so to it.
> In this way I can succeed in compiling, but when I run the binary, it
> exists the following errors: Error: clGetPlatformIDs failed. Error code :
> CL_PLATFORM_NOT_FOUND_KHR
>
> So I think if there is any one OpenCL runtime API existing in my program
> (host code), it cannot run correctly in the HSA enabled system. I think the
> reason is that I haven't installed the related GPU runtime environment, but
> HSA-AMD-driver instead. Is that correct?
>
> Thank you!
>
> Best Regards,
> Xiuhong
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HSAFoundation/CLOC/issues/3#issuecomment-71444932>.
>



-- 
With Best Regards
Prakash Raghavendra

**Comment by LiXiuhong** [comment]
I see. Thank you for your help.
