### ISSUE TITLE
Is CLOC open source or will it be?

### ISSUE THREAD

**Issue by rollingthunder** [HSAFoundation/CLOC#5]
I would really like to have a look at the source. 
If that is not realistic, is there another sample project for a language-to-HSAIL compiler?

**Comment by gstoner** [comment]
This is full C++ compiler that support HSA  Compiler and HSA runtime
https://bitbucket.org/multicoreware/cppamp-driver-ng/wiki/HSA%20Support%20Status


On May 11, 2015, at 4:09 PM, rollingthunder <notifications@github.com<mailto:notifications@github.com>> wrote:


I would really like to have a look at the source.
If that is not realistic, is there another sample project for a language-to-HSAIL compiler?

**Comment by gregrodgers** [comment]
Just cleaning up old issues.   This was answered last year.
