### ISSUE TITLE
snack helloworld example generate .snackwrap.c even though compiling with -c option

### ISSUE THREAD

**Issue by ohsul92** [HSAFoundation/CLOC#6]
Hi.
Few weeks ago, I bought kaveri A10-7850K from AMD which supports hsa and made the full computer
for the kaveri with DRAM, SSD etc. I'm trying to compare the performance between hsa mode and non-hsa mode using the kaveri.
First, I want to compile the OpenCL example in hsa mode. I installed hsa runtime, driver, and CLOC. When I tried to compile the helloworld example in snack directory, I snacked the hw.cl with the command 'snack.sh -c hw.cl'. However, many lines of errors appear such as 
/tmp/snk_17760/hw.snackwrap.c:148:40: error: unknown type name 'hsa_ext_brig_module_t'
                                        hsa_ext_brig_module_t* brig_module,
                                        ^
Even though I used the -c option, it generates .snackwrap.c. What should I do to solve these errors?
And does anyone have any Idea to compare the performance between hsa mode and non-hsa mode by using OpenCL code?

**Comment by alienanthill** [comment]
Hi,

Which branch are you using? The master branch does not work with the current release of HSA. Can you try the cloc 0.9 branch instead ?

**Comment by ohsul92** [comment]
Hi. Thank you for your reply.
I tried the cloc 0.9 branch and I got the different problem.
When I run CLOC/examples/hsa/vector_copy, it works without any problem but CLOC/examples/snack/vector_copy occurs segmentation fault at the line that call vcopy funcion.
All the examples in snack directory have the same problem.
I don't know what the problem is.
Do you have any idea?

**Comment by alienanthill** [comment]
Hi,

Can you put it under gdb and check where it segfaults ?

**Comment by ohsul92** [comment]
Segmentation fault occurs at the line of fuction call to kernel fuction(?)
For the hello world example,

int main(int argc, char* argv[]) {                                              
    char* input = "Gdkkn\x1FGR@\x1FVnqkc";                                      
    size_t strlength = strlen(input);                                           
    char *output = (char*) malloc(strlength + 1);                               
    char *secode = (char*) malloc(strlength + 1);                               
    char *output2 = (char*) malloc(strlength + 1);                              
                                                                                
        SNK_INIT_LPARM(lparm,strlength);                                        
        decode(input,output,lparm);                                             
        output[strlength] = '\0';                                               
        printf("Decoded       :%s\n",output);                                   
        /* Show we can call multiple functions in the .cl file */               
        super_encode(output,secode,lparm);                                      
        printf("Super encoded :%s\n",secode);                                   
        super_decode(secode,output2,lparm);                                     
        printf("Super decoded :%s\n",output2);                                  
       /* Show we can call same function multiple times */                      
        decode(secode,output,lparm);                                            
        decode(output,output2,lparm);                                           
    printf("Decoded twice :%s\n",output2);                                      
    free(output);                                                               
    free(secode);                                                               
    free(output2);                                                              
    return 0;                                                                   
}               

segmentation fault occurs at the line of calling decode(input, output, lparam);
All the other examples have same situation.
I still really don't know what the problem is.

gcc -o -g HelloWorld hw.o HelloWorld.c -L/opt/hsa/lib -lhsa-runtime64 

./HelloWorld
./buildrun.sh: line 41:  5854 Segmentation fault      (core dumped) ./HelloWorld
surim@hsa:~/examples/snack/helloworld$

**Comment by ohsul92** [comment]
I have another question.
Is each character for "hello world" decoded by seperated core?
I'm wondering that the characters are decoded in parallel in GPU in this example.
I'm trying to compare the performance of OpenCL and HSA.
so if the helloworld example is the example of hsa, I can compare it to the helloworld example of OpenCL.

Thanks.

**Comment by gregrodgers** [comment]
Sorry for the delayed response.   HelloWorld is not a good performance measure.  But yes, the characters are decoded in parallel by different GPU "workers".  GPUs use SIMT, so the kernel is executed in lockstep by each worker of a work group.  YES, if the number of workitems you have (in the helloworld case, this is strlength) is less than the groupsize, you have some wasted workers (GPU cores).
